name: dev

# local paths are relative to the project's root dir

local:
    actors_input_dir: data/input/actors
    politician_output_dir: data/output/politician

    plenary_html_dir: data/input/plenary/html
    plenary_json_dir: ../voting-data-publications

    document_pdf_dir: data/input/documents
    document_text_dir: data/output/documents/txt
    document_summary_dir: data/output/documents/summary

gdrive:
    document_text_dir: storage-local/documents/text
    document_summary_dir: storage-local/documents/summary

elastic:
    host: transparent-democrac-6644447145.eu-west-1.bonsaisearch.net
